---
- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка необходимых пакетов
  apt:
    name:
      - wget
      - curl
      - gnupg
      - lsb-release
      - postgresql
    state: present

- name: Проверка существования пользователя postgres
  command: id -u postgres
  register: postgres_user_check
  ignore_errors: yes

- name: Создание пользователя postgres
  user:
    name: postgres
    system: yes
    shell: /bin/bash
  when: postgres_user_check.rc != 0

- name: Добавление ключа GPG для PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Добавление репозитория PostgreSQL
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
